### ISSUE TITLE
Category Suggestion: Vacation Bible School System

### ISSUE THREAD

**Issue by prabhu-qea** [meichthys/opensource_church_software#2]
Hi,

I have developed an open source Vacation Bible School System for churches. A simple solution based on PHP, AJAX and CSS.

https://github.com/prabhu-qea/Vacation-Bible-School-System

Kindly review and add it to the suggested softwares or under appropriate section, if you are happy, please.

Regards.
Prabhu.

**Comment by meichthys** [comment]
This is very neat, thanks for sharing, and may you be blessed for your work on this, and for sharing it freely!

**Comment by prabhu-qea** [comment]
Thank You! God Bless You too!!

**Comment by prabhu-qea** [comment]
Appreciate if you can add this to the existing list, please

**Comment by meichthys** [comment]
I will shortly

**Comment by prabhu-qea** [comment]
Thank You!
